# Generated by Django 5.1.1 on 2024-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopping_cart',
            field=models.CharField(default=1, max_length=255, verbose_name='a'),
            preserve_default=False,
        ),
    ]
