# Generated by Django 5.1.1 on 2024-09-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to='main.game'),
        ),
    ]
